nginx:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes_from:
    - php
  volumes:
    - ./.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: ./.docker/php/
  volumes:
    - ./web:/srv/web/
    - ./vendor:/srv/vendor/
  links:
    - mongo:mongo

mongo:
  image: mongo:3.5
  ports:
    - "27017:27017"
